### PR TITLE
[WIP] split out store-streaming

### PR DESCRIPTION
**Pull request by ocramz**
I've started addressing #51 : 
* (temporary) bugfix version bump to 0.3.4.4 in store
* moved Data.Store.Streaming and Data.Store.Streaming.Internal to store-streaming
* removed conduit and streaming-commons dependency from store
* moved test/Data.Store.StreamSpec to store-streaming

This is still WIP because the LTS version of `store` needs to be bumped (and with it all dependency bounds I think) :

```
Error: While constructing the build
plan, the following exceptions were
encountered:

In the dependencies
for store-streaming-0.1.0.0:
    store-0.4.2 from stack configuration
                does not match >=0.4.3.4
```

Eager to hear feedback!

### CODE REVIEW

**Comment by mgsloan** [comment]
Cool, thanks!  I don't think that store-streaming should get its own .travis.yml.

I think it makes sense to delete the cabal files from the repo (require hpack).  This way we won't need to deal with conflicts / commit generated code.

**Comment by ocramz** [comment]
@mgsloan I;ve applied your feedback to the latest PR, let me know!

**Comment by mgsloan** [comment]
Thanks!  Sorry for the huge delay in getting to this, been letting github notification slide too much

**Comment by ocramz** [comment]
No prob, thanks for merging!

**Comment by mgsloan** [comment]
FYI this is now released http://hackage.haskell.org/package/store-streaming

**Pull request merged**
